

import junit.framework.TestCase;

/**
 * The class <code>ColouringTest</code> contains tests for the class {@link
 * <code>MainThread</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 27/11/12 12:23 PM
 *
 * @author darrylhill
 *
 * @version $Revision$
 */
public class ColouringTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public ColouringTest(String name) {
		super(name);
	}

	/**
	 * Run the void initialize() method test
	 * The neighbours are recorded at inception and used
	 * to determine connections. Each neighbour instance 
	 * has a reference to two sensors that are neighbours.
	 * So we run through all of 
	 * them and ensure that no two are coloured alike
	 */
	public void testInitialize() {
		
		MainThread main = new MainThread(null);
		main.initialize(10000);
		for (Neighbour n:main.neighbours){
			if (n._sensor1.getDelay()==n._sensor2.getDelay()){
				assertTrue(false);
			}
		}
		//assertTrue(false);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = initialize()
 * package = 
 * package.sourceFolder = sensor-project/src
 * superclassType = junit.framework.TestCase
 * testCase = ColouringTest
 * testClassType = MainThread
 */