import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JOptionPane;

/**
 * Used in conjunction with the MakeAverage class to generate graphs.
 * Reads in files generated by the MakeAverage class and outputs 
 * html files to be displayed in a browser.
 *
 */
public class MakeGraph {
	int n = 40;
	String k, tests;
	
	String top = "<html>\n"+
  "<head>\n"+
    "<script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script>\n"+
    "<script type=\"text/javascript\">\n"+
      "google.load(\"visualization\", \"1\", {packages:[\"corechart\"]});\n"+
      "google.setOnLoadCallback(drawChart);\n"+
      "function drawChart() {\n"+
        "var data = google.visualization.arrayToDataTable([\n"+
          "['Time', 'ARA', 'RSRMA','RSRMA\\''],\n";
	
	//for testing, soon deprecated
	String middle = ""+
	          "['2004',  1000,      400, 200],\n"+
	          "['2005',  1170,      460, 100],\n"+
	          "['2006',  660,       1120, 400],\n"+
	          "['2007',  1030,      540, 588]\n";
	
	String bottom1 = ""+
			 "]);\n"+

		        "var options = {\n"+
		          "title: 'Algorithm Performance for n = ";
	String bottom2 = " and k = ";
	String bottom3 = "',\n"+
		          "hAxis: {title: 'Rounds', titleTextStyle: {color: 'red'}},\n"+
		          "vAxis: {title: 'Percentage of Sensors Discovered', titleTextStyle: {color: 'red'}}\n"+

		        "};\n"+

		        "var chart = new google.visualization.LineChart(document.getElementById('chart_div'));\n"+
		        "chart.draw(data, options);\n"+
		      "}\n"+
		    "</script>\n"+
		  "</head>\n"+
		  "<body>\n"+
		    "<div id=\"chart_div\" style=\"width: 900px; height: 500px;\"></div>\n"+
		  "</body>\n"+
		"</html>\n";
	
	
	BufferedWriter graph;
	
	public MakeGraph(int n, String k){

		
		/*String s = (String)JOptionPane.showInputDialog(
		                    null,
		                    "How many sensors?",
		                    "Customized Dialog",
		                    JOptionPane.PLAIN_MESSAGE,
		                    null,null, null);
				
		if ((s == "")||(s==null)){
			System.exit(0);
		}
		n = Integer.parseInt(s);
		if (n == 0){
			System.exit(0);
		}
		
		k = (String)JOptionPane.showInputDialog(
                null,
                "k value?",
                "Customized Dialog",
                JOptionPane.PLAIN_MESSAGE,
                null,null, null);*/
		this.k = k;
		this.n = n;
		
		String middle = null;
		try {
			middle = makeMiddle();
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		try{
			// Create file 
			String fs = System.getProperty("file.separator");
			String pre = "graphfiles"+fs;
			FileWriter fstream = new FileWriter(pre+"graph"+n+"k"+k+".html");
			graph = new BufferedWriter(fstream);
			graph.write(top);
			graph.write(middle);
			graph.write(bottom1);
			//writing in the number of sensors in the title
			graph.write(Integer.toString(n));
			graph.write(bottom2);
			graph.write(k);
			graph.write(bottom3);
		}catch (Exception e){//Catch exception if any
			System.err.println("Error: " + e.getMessage());
		}finally{
			try {
				graph.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		
	}
	
	public String makeMiddle() throws IOException{
		StringBuffer middle = new StringBuffer();
		/*
		 * 	String middle = ""+
	          "['2004',  1000,      400, 200],\n"+
	          "['2005',  1170,      460, 100],\n"+
	          "['2006',  660,       1120, 400],\n"+
	          "['2007',  1030,      540, 588]\n";
	          
	          This is your target
		 */
		FileReader ARAfile = null;
		FileReader RSRMAfile = null;
		FileReader RSRMApfile = null;

		//Stat__S-3_T-0_A-ARA_K4
		try {
			String fs = System.getProperty("file.separator");
			String pre = "average"+fs;
			ARAfile = new FileReader(pre+"Stat__S-"+n+"_AVERAGE_A-ARA_K"+k+".txt");
			RSRMAfile = new FileReader(pre+"Stat__S-"+n+"_AVERAGE_A-RSRMA_K"+k+".txt");
			RSRMApfile= new FileReader(pre+"Stat__S-"+n+"_AVERAGE_A-RSRMA'_K"+k+".txt");
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		BufferedReader ARA = new BufferedReader(ARAfile);
		BufferedReader RSRMA = new BufferedReader(RSRMAfile);
		BufferedReader RSRMAp = new BufferedReader(RSRMApfile);
		int count = 0;
		String str;
		boolean moreARA = true, moreRSRMA = true, moreRSRMAp = true;
		while (true){
			count ++;
			middle.append("["+count+",");
			/*
			 * The stats files are not always the same length.
			 * If there are no more lines presumably that one had
			 * discovered all the sensors, so we assign it 1
			 */
			//ARA
			if (moreARA){
				str = ARA.readLine();
				if (str == null){
					moreARA = false;
					str = "1";
				}
				
			}else{
				str = "1";
			}
			middle.append(str+",");
			
			//RSRMA
			if (moreRSRMA){
				str = RSRMA.readLine();
				if (str == null){
					moreRSRMA = false;
					str = "1";
				}
			}else{
				str = "1";
			}
			middle.append(str+",");
			
			//RSRMAp
			if (moreRSRMAp){
				str = RSRMAp.readLine();
				if (str == null){
					moreRSRMAp = false;
					str = "1";
				}
			}else{
				str = "1";
			}
			middle.append(str+"],\n");
			if ((!moreARA)&&(!moreRSRMA)&&(!moreRSRMAp)){
				break;
			}
			if (count > 4000){
				break;
			}
		}
		//delete the last comma
		middle.deleteCharAt(middle.length()-2);
		return middle.toString();
	}
	
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		//new MakeGraph();

	}

}
