import junit.framework.TestCase;

/**
 * The class <code>SensorTest</code> contains tests for the class {@link
 * <code>Sensor</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 28/11/12 3:16 AM
 *
 * @author darrylhill
 *
 * @version $Revision$
 */
public class SensorTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public SensorTest(String name) {
		super(name);
	}

	/**
	 * Run the int inSector(Point) method test
	 */
	public void testInSector() {
		// add test code here
		Debug.setDebug(true);
		Sensor sensor1 = new Sensor(1, 20, 20, 50, 12);
		Sensor sensor2 = new Sensor(1, 30, 20, 50, 12);
		
		int sector1 = sensor1.inSector(sensor2.getPoint());
		int sector2 = sensor2.inSector(sensor1.getPoint());
		System.out.println("sector1: "+sector1);
		System.out.println("sector2: "+sector2);
		for (int i = 3; i < 13; i ++){
			System.out.printf("i=%d, Mod value: %d\n",i, 360%i);
		}
		System.out.printf("360 / 11 = %d\n",360/11);;
		//Point p2 = null;
		// This class does not have a public, no argument constructor,
		// so the inSector() method can not be tested
		//assertTrue(false);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = inSector(QPoint;)
 * package = 
 * package.sourceFolder = sensor-project/src
 * superclassType = junit.framework.TestCase
 * testCase = SensorTest
 * testClassType = Sensor
 */